apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xenorchestra-cloud-controller-manager.fullname" . }}
  labels:
    {{- include "xenorchestra-cloud-controller-manager.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
  selector:
    matchLabels:
      {{- include "xenorchestra-cloud-controller-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.config }}
        checksum/config: {{ toJson .Values.config | sha256sum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xenorchestra-cloud-controller-manager.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xenorchestra-cloud-controller-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers: {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --v={{ .Values.logVerbosityLevel }}
            - --cloud-provider=xenorchestra
            - --cloud-config=/etc/xenorchestra/xo-config.yaml
            - --controllers={{- trimAll "," (include "xenorchestra-cloud-controller-manager.enabledControllers" . ) }}
            - --leader-elect-resource-name=cloud-controller-manager-xenorchestra
            - --use-service-account-credentials
            - --secure-port=10258
            - --authorization-always-allow-paths=/healthz,/livez,/readyz,/metrics
          {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvs }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: 10258
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
              scheme: HTTPS
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cloud-config
              mountPath: /etc/xenorchestra
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "xenorchestra-cloud-controller-manager.selectorLabels" . | nindent 20 }}
                topologyKey: topology.kubernetes.io/zone
              weight: 1
      {{- end }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "xenorchestra-cloud-controller-manager.selectorLabels" . | nindent 14 }}
      volumes:
        {{- if .Values.existingConfigSecret }}
        - name: cloud-config
          secret:
            secretName: {{ .Values.existingConfigSecret }}
            items:
              - key: {{ .Values.existingConfigSecretKey }}
                path: xo-config.yaml
            defaultMode: 416
        {{- else }}
        - name: cloud-config
          secret:
            secretName: {{ include "xenorchestra-cloud-controller-manager.fullname" . }}
            defaultMode: 416
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
