{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xenorchestra-cloud-controller-manager.fullname" . }}
  labels:
    {{- include "xenorchestra-cloud-controller-manager.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: {{ toYaml .Values.config | b64enc | quote }}
{{- end }}
